### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'random_fps'

### ISSUE THREAD

**Issue by linQian99** [V-DETR/V-DETR#11]
Thank you for your great work! May I ask how to fix this problem.

`(VDETR) lin@linDesktop:~/work/V-DETR$ python main.py --dataset_name scannet --dataset_root_dir /home/lin/work/V-DETR/scannet/ --meta_data_dir /home/lin/work/V-DETR/scannet/meta_data/ --ngpus 1 --batchsize_per_gpu 8 /home/lin/anaconda3/envs/VDETR/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  warnings.warn(
Called with args: Namespace(angle_conf=False, angle_nms=False, angle_type='', auto_test=False, axis_align_test=False, base_lr=0.0007, batchsize_per_gpu=8, checkpoint_dir=None, clip_gradient=0.1, cls_loss='focalloss_0.25', color_contrastp=0.0, color_drop=0.0, color_jitterp=0.0, color_mean=-1, coloraug_sunrgbd=False, conf_thresh=0.0, dataset_name='scannet', dataset_num_workers=8, dataset_root_dir='/home/lin/work/V-DETR/scannet/', dec_dim=256, dec_dropout=0.1, dec_ffn_dim=256, dec_nhead=4, dec_nlayers=9, depth=34, dist_url='tcp://localhost:12345', empty_pt_thre=5, enc_dim=256, eval_every_epoch=10, filt_empty=True, filter_biases_wd=False, final_lr=1e-06, hard_anchor=False, hue_sat='0.5_0.2_0.0', inplanes=64, iou_type='giou', is_bilable=True, layer_idx=0, log_every=10, log_metrics_every=20, log_scale=512, loss_angle_cls_weight=0.1, loss_angle_reg_weight=0.5, loss_center_weight=1, loss_giou_weight=2, loss_no_object_weight=0, loss_sem_cls_weight=3, loss_size_weight=0.5, lr_scheduler='cosine', matcher_anglecls_cost=0, matcher_anglereg_cost=0, matcher_center_cost=1, matcher_cls_cost=3, matcher_giou_cost=2, matcher_objectness_cost=0, matcher_size_cost=0.5, max_epoch=540, meta_data_dir='/home/lin/work/V-DETR/scannet/meta_data/', mink_syncbn=True, minkowski=True, mlp_act='relu', mlp_dropout=0.3, mlp_norm='bn1d', mlp_sep=True, model_name='vdetr', ngpus=1, nms_iou=0.25, no_3d_nms=False, no_cls_nms=False, no_first_repeat=True, no_mink_first_pool=True, no_per_class_proposal=False, normal_trans=False, nqueries=1024, nsemcls=-1, num_points=100000, num_stages=4, point_cls_loss_weight=0.05, pos_for_key=False, preenc_npoints=4096, proj_nohid=True, q_content='random', querypos_mlp=True, repeat_num=5, rot_ratio=5.0, rotated_nms=False, rpe_dim=128, rpe_quant='bilinear_4_10', save_separate_checkpoint_every_epoch=1, scale_ratio=0.4, seed=0, share_selfattn=False, start_epoch=-1, stem_bn=True, step_epoch='', test_ckpt=None, test_no_nms=False, test_only=False, test_size=False, trans_ratio=0.4, use_cls_confidence_only=False, use_color=False, use_fpn=True, use_normals=False, use_old_type_nms=False, use_superpoint=False, voxel_size=0.01, wandb_activate=True, wandb_entity=None, wandb_key='', wandb_project='vdetr', warm_lr=1e-06, warm_lr_epochs=9, weight_decay=0.1, woexpand_conv=True, xyz_color=False)
/home/lin/work/V-DETR/scannet/meta_data/scannetv2_train.txt
kept 0 scans out of 1201
train 0 scans before filter
train 0 scans after filter
/home/lin/work/V-DETR/scannet/meta_data/scannetv2_val.txt
kept 0 scans out of 312
val 0 scans before filter
val 0 scans after filter
random init backbone
/home/lin/anaconda3/envs/VDETR/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
random init decoder
Traceback (most recent call last):
  File "main.py", line 605, in <module>
    launch_distributed(args)
  File "main.py", line 593, in launch_distributed
    main(local_rank=0, args=args)
  File "main.py", line 509, in main
    model = build_model(args, dataset_config)
  File "/home/lin/work/V-DETR/models/__init__.py", line 9, in build_model
    model = MODEL_FUNCS[args.model_name](args, dataset_config)
  File "/home/lin/work/V-DETR/models/model_vdetr.py", line 454, in build_vdetr
    model = ModelVDETR(
  File "/home/lin/work/V-DETR/models/model_vdetr.py", line 87, in __init__
    self.random_fps = args.random_fps
AttributeError: 'Namespace' object has no attribute 'random_fps'
`

**Comment by Salieri0515** [comment]
> Thank you for your great work! May I ask how to fix this problem.
> 
> `(VDETR) lin@linDesktop:~/work/V-DETR$ python main.py --dataset_name scannet --dataset_root_dir /home/lin/work/V-DETR/scannet/ --meta_data_dir /home/lin/work/V-DETR/scannet/meta_data/ --ngpus 1 --batchsize_per_gpu 8 /home/lin/anaconda3/envs/VDETR/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS`not set. MinkowskiEngine will automatically set`OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS`manually, please export it on the command line before running a python script. e.g.`export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24. warnings.warn( Called with args: Namespace(angle_conf=False, angle_nms=False, angle_type='', auto_test=False, axis_align_test=False, base_lr=0.0007, batchsize_per_gpu=8, checkpoint_dir=None, clip_gradient=0.1, cls_loss='focalloss_0.25', color_contrastp=0.0, color_drop=0.0, color_jitterp=0.0, color_mean=-1, coloraug_sunrgbd=False, conf_thresh=0.0, dataset_name='scannet', dataset_num_workers=8, dataset_root_dir='/home/lin/work/V-DETR/scannet/', dec_dim=256, dec_dropout=0.1, dec_ffn_dim=256, dec_nhead=4, dec_nlayers=9, depth=34, dist_url='tcp://localhost:12345', empty_pt_thre=5, enc_dim=256, eval_every_epoch=10, filt_empty=True, filter_biases_wd=False, final_lr=1e-06, hard_anchor=False, hue_sat='0.5_0.2_0.0', inplanes=64, iou_type='giou', is_bilable=True, layer_idx=0, log_every=10, log_metrics_every=20, log_scale=512, loss_angle_cls_weight=0.1, loss_angle_reg_weight=0.5, loss_center_weight=1, loss_giou_weight=2, loss_no_object_weight=0, loss_sem_cls_weight=3, loss_size_weight=0.5, lr_scheduler='cosine', matcher_anglecls_cost=0, matcher_anglereg_cost=0, matcher_center_cost=1, matcher_cls_cost=3, matcher_giou_cost=2, matcher_objectness_cost=0, matcher_size_cost=0.5, max_epoch=540, meta_data_dir='/home/lin/work/V-DETR/scannet/meta_data/', mink_syncbn=True, minkowski=True, mlp_act='relu', mlp_dropout=0.3, mlp_norm='bn1d', mlp_sep=True, model_name='vdetr', ngpus=1, nms_iou=0.25, no_3d_nms=False, no_cls_nms=False, no_first_repeat=True, no_mink_first_pool=True, no_per_class_proposal=False, normal_trans=False, nqueries=1024, nsemcls=-1, num_points=100000, num_stages=4, point_cls_loss_weight=0.05, pos_for_key=False, preenc_npoints=4096, proj_nohid=True, q_content='random', querypos_mlp=True, repeat_num=5, rot_ratio=5.0, rotated_nms=False, rpe_dim=128, rpe_quant='bilinear_4_10', save_separate_checkpoint_every_epoch=1, scale_ratio=0.4, seed=0, share_selfattn=False, start_epoch=-1, stem_bn=True, step_epoch='', test_ckpt=None, test_no_nms=False, test_only=False, test_size=False, trans_ratio=0.4, use_cls_confidence_only=False, use_color=False, use_fpn=True, use_normals=False, use_old_type_nms=False, use_superpoint=False, voxel_size=0.01, wandb_activate=True, wandb_entity=None, wandb_key='', wandb_project='vdetr', warm_lr=1e-06, warm_lr_epochs=9, weight_decay=0.1, woexpand_conv=True, xyz_color=False) /home/lin/work/V-DETR/scannet/meta_data/scannetv2_train.txt kept 0 scans out of 1201 train 0 scans before filter train 0 scans after filter /home/lin/work/V-DETR/scannet/meta_data/scannetv2_val.txt kept 0 scans out of 312 val 0 scans before filter val 0 scans after filter random init backbone /home/lin/anaconda3/envs/VDETR/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:2894.) return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined] random init decoder Traceback (most recent call last): File "main.py", line 605, in <module> launch_distributed(args) File "main.py", line 593, in launch_distributed main(local_rank=0, args=args) File "main.py", line 509, in main model = build_model(args, dataset_config) File "/home/lin/work/V-DETR/models/__init__.py", line 9, in build_model model = MODEL_FUNCS[args.model_name](args, dataset_config) File "/home/lin/work/V-DETR/models/model_vdetr.py", line 454, in build_vdetr model = ModelVDETR( File "/home/lin/work/V-DETR/models/model_vdetr.py", line 87, in __init__ self.random_fps = args.random_fps AttributeError: 'Namespace' object has no attribute 'random_fps' `

Hi, @linQian99. I also encounter this problem when doing testing. 'random_fps' doesn't even exist in parser from main.py.  Have you solved the problem? Maybe just set it to false by default?

**Comment by Salieri0515** [comment]
I also found many other arguments don't exist in parser but they are needed in the class of APCalculator, such as use_old_type_nms, cls_nms, per_class_proposal, use_cls_confidence_only.

**Comment by fangyingjian1998** [comment]
# self.random_fps = args.random_fps
        self.random_fps =True
改写成这个样子就可以了
