### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Research-Code-123** [V-DETR/V-DETR#14]
Have you ever met this bug?

(vdetr) ~/Documents/OVOD/V-DETR# cd utils && python cython_compile.py build_ext --inplace
Traceback (most recent call last):
  File "cython_compile.py", line 20, in <module>
    include_dirs=INCLUDE_PATH
  File "/root/anaconda3/envs/vdetr/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1017, in cythonize
    aliases=aliases)
  File "/root/anaconda3/envs/vdetr/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 845, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/root/anaconda3/envs/vdetr/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 117, in nonempty
    raise ValueError(error_msg)
ValueError: 'box_intersection.pyx' doesn't match any files

Thanks

**Comment by NurbekkWARTO** [comment]
@Research-Code-123 https://github.com/V-DETR/V-DETR/issues/3#issuecomment-2068729914
