### ISSUE TITLE
Installation issues：'box_intersection.pyx' doesn't match any files

### ISSUE THREAD

**Issue by Inshsang** [V-DETR/V-DETR#3]
After executing cd utils && python cython_compile.py build_ext --inplace

Traceback (most recent call last):
  File "cython_compile.py", line 16, in <module>
    ext_modules = cythonize(
  File "/home/junjie/.conda/envs/htcvdetr/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1010, in cythonize
    module_list, module_metadata = create_extension_list(
  File "/home/junjie/.conda/envs/htcvdetr/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 845, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/home/junjie/.conda/envs/htcvdetr/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 117, in nonempty
    raise ValueError(error_msg)
ValueError: 'box_intersection.pyx' doesn't match any files

**Comment by JiayuXu829** [comment]
I have encountered the same problem. Have you resolved it?

**Comment by RyanG41** [comment]
@JiayuXu829 @Inshsang 
Hi, I think the codes in this repo is partly borrowed from another project "https://github.com/facebookresearch/3detr". The missing file "box_intersection.pyx" can be found in their repo folder "utils". Hope it helps.

**Comment by Inshsang** [comment]
@RyanG41 Thanks！ It works.
