### ISSUE TITLE
Question about some steps of the environment installment

### ISSUE THREAD

**Issue by linQian99** [V-DETR/V-DETR#5]
Thank you for your great work! May I ask a question about the environment installment.
I am trying to run this step.

``
 cd utils && python cython_compile.py build_ext --inplace
``

But following error log shows on the terminal.

``
V-DETR]$ cd utils && python cython_compile.py build_ext --inplace
Traceback (most recent call last):
  File "cython_compile.py", line 16, in <module>
    ext_modules = cythonize(
  File "/mnt/iusers01/eee01/v03515lq/.conda/envs/VDETR/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1010, in cythonize
    module_list, module_metadata = create_extension_list(
  File "/mnt/iusers01/eee01/v03515lq/.conda/envs/VDETR/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 845, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/mnt/iusers01/eee01/v03515lq/.conda/envs/VDETR/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 117, in nonempty
    raise ValueError(error_msg)
ValueError: 'box_intersection.pyx' doesn't match any files
``

It seems like because of the lack of the file box_intersection.pyx. Could you update it to the respository, plz ? Thank you for your time
![image](https://github.com/V-DETR/V-DETR/assets/160034625/951ceaf0-4419-4f8a-ad28-0177b8bbc66b)

**Comment by RyanG41** [comment]
Hi,

I think you can refer to [here](https://github.com/V-DETR/V-DETR/issues/3).

**Comment by yichaoshen-MS** [comment]
> Hi,
> 
> I think you can refer to [here](https://github.com/V-DETR/V-DETR/issues/3).

Thanks for your contribution, I will fix the problem very soon.

**Comment by linQian99** [comment]
solved
